client_secret: Vx1XFHryYMh7ekL96KOSqTWroUIGNi99
debug: false
disable_auto_update: true
disable_command_execute: false
disable_force_update: true
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: true
ip_report_period: 1800
report_delay: 4
server: dx.220704.xyz:443
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: true
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: 65088f50-2eeb-4aea-9cae-f76b3973e598
